### Credits to Beautiful Jekyll / Dean Attali for this theme
#### Beautiful Jekyll: "https://beautifuljekyll.com"

title: Ethical Hackers Club
author: Ameer Pornillos

navbar-links:
  About Me: "about"

avatar: "/assets/img/avatar-icon.png"

round-avatar: true


social-network-links:
  github: ameerpornillos
  twitter: ameerpornillos
  youtube: EthicalHackersClub

rss-description: An Information Security (InfoSec) blog. Learn ethical hacking, penetration testing, digital forensics and anything related to cyber security.

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

url-pretty: "EthicalHackers.club"

excerpt_length: 50

feed_show_excerpt: true

feed_show_tags: true

post_search: true

navbar-var-length: false

keywords: "penetration testing, ethical hacking, ethical hacker, ethical hackers club"

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

date_format: "%B %-d, %Y"

timezone: "Asia/Manila"
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 10

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      #comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap



